name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]

  workflow_dispatch:

jobs:
  windows:
    name: Release Windows x86_64
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:

    - name: Install tools
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install gcc-mingw-w64-x86-64 nasm

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) PLATFORM=mingw64 DESTDIR=bin

    - name: Create archive
      run: |
        7z a -r build/omega-engine-windows-x86_64.zip ./bin/*

    - uses: actions/upload-artifact@v7
      with:
        name: release-mingw64-x86_64
        path: build/omega-engine-windows-x86_64.zip
        if-no-files-found: error
        retention-days: 5
        
  linux:
    name: Release Linux x86_64
    runs-on: ubuntu-24.04
    container: debian:trixie
    strategy:
      fail-fast: false

    steps:

    - name: Install tools
      run: |
        apt-get -qq update
        apt-get install -y make gcc git cmake
        apt-get -y install libcurl4-openssl-dev libsdl3-dev libopenal-dev nasm

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) BUILD_SERVER=1 DESTDIR=bin

    - name: Create archive
      run: |
        tar -czf build/omega-engine-linux-x86_64.tar.gz -C bin .

    - uses: actions/upload-artifact@v7
      with:
        name: release-linux-x86_64
        path: build/omega-engine-linux-x86_64.tar.gz
        if-no-files-found: error
        retention-days: 5

  linux-arm:
    name: Release Linux arm64
    runs-on: ubuntu-24.04-arm
    container: debian:trixie
    strategy:
      fail-fast: false

    steps:

    - name: Install tools
      run: |
        apt-get -qq update
        apt-get install -y make gcc git cmake
        apt-get -y install libcurl4-openssl-dev libsdl3-dev libopenal-dev

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build
      run: |
        make install -j$(nproc) BUILD_SERVER=1 DESTDIR=bin

    - name: Create archive
      run: |
        tar -czf build/omega-engine-linux-arm64.tar.gz -C bin .

    - uses: actions/upload-artifact@v7
      with:
        name: release-linux-arm64
        path: build/omega-engine-linux-arm64.tar.gz
        if-no-files-found: error
        retention-days: 5

  macos:
    name: Release macOS universal2
    runs-on: macos-15
    strategy:
      fail-fast: false

    steps:

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build
      run: |
        ./make-macosx-ub2.sh
        hdiutil create -format UDZO -srcfolder build/release-darwin-universal2/OmegA.app build/omega-engine-macos-universal2.dmg

    - uses: actions/upload-artifact@v7
      with:
        name: release-darwin-universal2
        path: build/omega-engine-macos-universal2.dmg
        if-no-files-found: error
        retention-days: 5

  create-testing:
    if: github.event_name == 'workflow_dispatch'
    needs: [windows, linux, linux-arm, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8

      - name: Create binary archives
        run: |
          cp ./release-linux-x86_64/omega-engine-linux-x86_64.tar.gz .
          cp ./release-linux-arm64/omega-engine-linux-arm64.tar.gz .
          cp ./release-mingw64-x86_64/omega-engine-windows-x86_64.zip .
          cp ./release-darwin-universal2/omega-engine-macos-universal2.dmg .
      - name: Create latest build
        uses: czietz/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "development"
          prerelease: true
          title: Development Build
          files: |
            *.tar.gz
            *.zip
            *.dmg
